# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a35201b50dc2b63e6b9b133831189916a012a152f96c822f5b0569d099514ef10de288e64658b6d327c6075001b5089c6a92f644c5739b1c6664ebac9734af39

test:
  secret_key_base: 30dccb9c30a525e44c4b3d2f75e7970c23b3bd604a63162fa42e43c0f8bff2bfc25dcd75c0a007e90bfafb044f4adaa82304c1d9b9fc1aaceab2fc5ebe7246b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
